### ISSUE TITLE
missing icons

### ISSUE THREAD

**Issue by vinniec2** [Samueru-sama/pavucontrol-qt-AppImage#1] opened 2024-07-15 05:51 UTC
Strangely it becomes useful for me too that you created this appimage because I'm on a distro with pipewire but without pavucontrol.
However, I don't see the little icons inside the mixer
Can you see the image? up to the mouse pointer the lack of icons :)

![pavu_icon](https://github.com/user-attachments/assets/4fc0e0b9-1f0d-41f3-a844-9536179b5907)

**Comment by Samueru-sama** [comment] 2024-07-15 06:00
That's odd, here it is fine: 

![image](https://github.com/user-attachments/assets/f24e7693-4de4-4f7e-a48b-dd4077aee2be)

I had this issue with the icons (and that it wasn't following the system theme) when I made the appimage with the qt plugin in linuxdeploy. I stopped using it as that was the only way it could follow the system theme. 

That change means that you need to have qt5 installed in your system (**which you have**) for the appimage to work. that's odd that you have missing icons since this pavucontrol appimage really isn't much different as if you had it native in your system. 

Do you have other qt5 applications in your system? You might need to set the icon theme with qt5ct or something like that.

**Comment by Samueru-sama** [comment] 2024-07-15 06:09
Indeed the issue seems to be a missing env variable: 

![image](https://github.com/user-attachments/assets/f6352926-889e-4da6-80f4-ab31688e6069)

**Comment by Samueru-sama** [comment] 2024-07-15 07:13
I just pushed https://github.com/Samueru-sama/pavucontrol-qt-AppImage/commit/19311c083ecf67454df5682ec263a2ff1ee02fe6

Let me know if it fixes the issue. (wait a few minutes before downloading the appimage again)

**Comment by vinniec2** [comment] 2024-07-16 01:35
No I have tried them all, both the new build and by pre-posing "QT_QPA_PLATFORMTHEME=gtk3 ".
Maybe my distro is so minimal that I don't have those icons installed, could you tell me where they should be?

**Comment by Samueru-sama** [comment] 2024-07-16 01:38
> No I have tried them all, both the new build and by pre-posing "QT_QPA_PLATFORMTHEME=gtk3 ". Maybe my distro is so minimal that I don't have those icons installed, could you tell me where they should be?

Do you have any errors in the terminal when launching the appimage? 

What distro and desktop environment are you using?

Do you have this issue with other qt5 applications?

**Comment by vinniec2** [comment] 2024-07-16 01:41
no errors, the distro is nemesis 24.06, a version with portable artix modules (itself version of arch without systemd)

**Comment by Samueru-sama** [comment] 2024-07-16 01:47
> no errors, the distro is nemesis 24.06, a version with portable artix modules (itself version of arch without systemd). https://sourceforge.net/projects/nemesis-linux/

Are you using the LXQT, XFCE or CINNAMON version?

------------------------------------------------------------

Open a terminal window and run the following. 

`echo $XDG_CURRENT_DESKTOP`
`echo $QT_QPA_PLATFORMTHEME`

I actually use artix linux myself btw, so that's odd that you have this issue.

**Also I need to know if you have this issue with other qt5 applications?** Because if true it might be that you don't have the icon theme configured at all.

**Comment by Samueru-sama** [comment] 2024-07-16 01:50
Do you have the issue with this appimage? It uses qt5 as well: https://github.com/JonMagon/KDiskMark/releases/tag/3.1.4

**Comment by vinniec2** [comment] 2024-07-16 01:50
Then I have xfce, the first command returns xfce the second command output blank.
I don't seem to currently have this problem, in qt5 I used opensnitch which doesn't seem to have a problem (but maybe the icons are all their own).
I have tried anki portable version but it doesn't seem to have a problem.
I can tell you that qt6 isn't there installed by default (at least it seems to because ank qt-6 portable version doesn't start for me).

**Comment by vinniec2** [comment] 2024-07-16 01:52
> Do you have the same issue with this appimage? It uses qt5 as well: https://github.com/JonMagon/KDiskMark/releases/tag/3.1.4

a moment I try

**Comment by vinniec2** [comment] 2024-07-16 01:55
![kdisk](https://github.com/user-attachments/assets/7b1f2dda-e6ac-41ce-8b75-02c583c60e8c)
everything seems to be regular, there is the charging icon with arrows

**Comment by Samueru-sama** [comment] 2024-07-16 01:59
Alright I'm out of ideas. 

Try installing qt5ct, that would be `sudo pacman -S qt5ct`

**Comment by vinniec2** [comment] 2024-07-16 02:04
yes, with this package I can see everything, in all your versions of pavucontrol, even the previous one and even without environment variable

**Comment by Samueru-sama** [comment] 2024-07-16 02:09
> yes, with this package I can see everything, in all your versions of pavucontrol, even the previous one and even without environment variable

Good, I still need to figure out a way to display the icons without qt5ct installed.

**Comment by vinniec2** [comment] 2024-07-16 02:17
is strange because very little stuff was installed with that package:
```
tree
.
├── usr
│   ├── bin
│   │   └── qt5ct
│   ├── include
│   ├── lib
│   │   ├── cmake
│   │   │   ├── Qt5Gui
│   │   │   │   ├── Qt5Gui_QSvgIconPlugin.cmake
│   │   │   │   └── Qt5Gui_QSvgPlugin.cmake
│   │   │   └── Qt5Svg
│   │   │       ├── Qt5SvgConfig.cmake
│   │   │       └── Qt5SvgConfigVersion.cmake
│   │   ├── libQt5Svg.prl
│   │   ├── libQt5Svg.so -> libQt5Svg.so.5.15.14
│   │   ├── libQt5Svg.so.5 -> libQt5Svg.so.5.15.14
│   │   ├── libQt5Svg.so.5.15 -> libQt5Svg.so.5.15.14
│   │   ├── libQt5Svg.so.5.15.14
│   │   ├── libqt5ct-common.so -> libqt5ct-common.so.1.8
│   │   ├── libqt5ct-common.so.1.8
│   │   ├── pkgconfig
│   │   │   └── Qt5Svg.pc
│   │   └── qt
│   │       ├── mkspecs
│   │       │   └── modules
│   │       │       ├── qt_lib_svg.pri
│   │       │       └── qt_lib_svg_private.pri
│   │       └── plugins
│   │           ├── iconengines
│   │           │   └── libqsvgicon.so
│   │           ├── imageformats
│   │           │   └── libqsvg.so
│   │           ├── platformthemes
│   │           │   └── libqt5ct.so
│   │           └── styles
│   │               └── libqt5ct-style.so
│   └── share
│       ├── applications
│       │   └── qt5ct.desktop
│       ├── licenses
│       │   ├── qt5-svg -> /usr/share/licenses/qt5-base
│       │   └── qt5ct
│       │       └── LICENSE
│       └── qt5ct
│           ├── colors
│           │   ├── airy.conf
│           │   ├── darker.conf
│           │   ├── dusk.conf
│           │   ├── ia_ora.conf
│           │   ├── sand.conf
│           │   ├── simple.conf
│           │   └── waves.conf
│           └── qss
│               ├── fusion-fixes.qss
│               ├── scrollbar-simple.qss
│               ├── sliders-simple.qss
│               ├── tooltip-simple.qss
│               └── traynotification-simple.qss
└── var
    └── lib
        └── pacman
            └── local
                ├── qt5-svg-5.15.14+kde+r5-1
                │   ├── desc
                │   ├── files
                │   └── mtree
                └── qt5ct-1.8-1
                    ├── desc
                    ├── files
                    └── mtree

31 directories, 39 files
```

**Comment by Samueru-sama** [comment] 2024-07-16 02:27
I actually tested putting the libraries from qt5ct in the pavucontrol appimage and it still doesn't work if qt5ct isn't installed kekw

**Comment by vinniec2** [comment] 2024-07-16 02:35
maybe installing qt5ct triggers some scripts to start?
But how are you testing it, did you install nemesis?

**Comment by vinniec2** [comment] 2024-07-16 02:39
in nemesis, logging onto the command line as root, there is a command called "changes-time", it lists all the changes in the system files from x minutes before the current time.
I might try rebooting, installing qt5ct and see what changes in the system files outside of the qt5ct files, then I can't think of anything else :D

**Comment by Samueru-sama** [comment] 2024-07-16 02:44
>But how are you testing it, did you install nemesis?

I can replicate the issue in artix if I remove `qt5ct` from the system.

**Comment by vinniec2** [comment] 2024-07-16 02:45
Oh, I'll try to remove the package, see if it stops working in real time

**Comment by vinniec2** [comment] 2024-07-16 02:51
Ok, is something that's in /usr/lib

**Comment by vinniec2** [comment] 2024-07-16 02:59
/usr/lib/qt/plugins/iconengines/libqsvgicon.so
We have it!

**Comment by Samueru-sama** [comment] 2024-07-16 03:13
> /usr/lib/qt/plugins/iconengines/libqsvgicon.so We have it! removing this is enough to make the icons disappear, I don't know if removing anything else as well

That's the lib responsible for rendering svg icons. 

I'm going to test if I have luck using go-appimagetool to deploy, it has this condition in the [code](https://github.com/probonopd/go-appimage/blob/master/src/appimagetool/appdirtool.go#L1300) that makes it deploy the `iconengines` directory in the AppDir if `libQt5Gui.so.5` gets deployed which is the case here.

**Comment by vinniec2** [comment] 2024-07-16 03:16
also this /usr/lib/libQt5Svg.so.5 
I'm tryng the rest

**Comment by vinniec2** [comment] 2024-07-16 03:20
I think these three files are all that are needed:
/usr/lib/qt/plugins/iconengines/libqsvgicon.so
/usr/lib/libQt5Svg.so.5 (symlink)
/usr/lib/libQt5Svg.so.5.15.14

**Comment by vinniec2** [comment] 2024-07-16 03:22
> > /usr/lib/qt/plugins/iconengines/libqsvgicon.so We have it! removing this is enough to make the icons disappear, I don't know if removing anything else as well
> 
> That's the lib responsible for rendering svg icons.
> 
> I'm going to test if I have luck using go-appimagetool to deploy, it has this condition in the [code](https://github.com/probonopd/go-appimage/blob/master/src/appimagetool/appdirtool.go#L1300) that makes it deploy the `iconengines` directory in the AppDir if `libQt5Gui.so.5` gets deployed which is the case here.

I'm hoping

**Comment by Samueru-sama** [comment] 2024-07-16 04:44
> > > /usr/lib/qt/plugins/iconengines/libqsvgicon.so We have it! removing this is enough to make the icons disappear, I don't know if removing anything else as well
> > 
> > 
> > That's the lib responsible for rendering svg icons.
> > I'm going to test if I have luck using go-appimagetool to deploy, it has this condition in the [code](https://github.com/probonopd/go-appimage/blob/master/src/appimagetool/appdirtool.go#L1300) that makes it deploy the `iconengines` directory in the AppDir if `libQt5Gui.so.5` gets deployed which is the case here.
> 
> I'm hoping

didn't work lol

You can run this script in your PC to test: 

```
#!/bin/sh

# TURNING THE NATIVE DEBIAN PACKAGE INTO AN APPIMAGE BECAUSE I CAN'T GET THIS TO COMPILE ON DEBIAN 20.04 KEK.
set -u
ARCH=x86_64
APP=pavucontrol-qt
APPDIR="$APP.AppDir"
REPO="http://ftp.us.debian.org/debian/pool/main/p/pavucontrol-qt/pavucontrol-qt_1.2.0-1_amd64.deb"
EXEC="$APP"
ICON="https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-icon-theme/master/Papirus/64x64/apps/yast-sound.svg"
APPIMAGETOOL=$(wget -q https://api.github.com/repos/probonopd/go-appimage/releases -O - | sed 's/[()",{} ]/\n/g' | grep -oi 'https.*continuous.*tool.*x86_64.*mage$' | head -1)

# CREATE DIRECTORIES
[ -n "$APP" ] && mkdir -p ./"$APP/$APPDIR"/tmp && cd ./"$APP/$APPDIR"/tmp || exit 1

# DOWNLOAD DEBIAN PACKAGE
CURRENTDIR="$(dirname "$(readlink -f "$0")")" # DO NOT MOVE THIS
wget $REPO && ar vx ./"$APP"* && tar fx ./data.tar* && mv ./usr .. && cd .. && rm -rf ./tmp || exit 1

# Desktop & Icon
cp ./usr/share/applications/*.desktop ./ && wget "$ICON" -O ./multimedia-volume-control.svg || exit 1
mkdir -p ./usr/share/icons/hicolor/scalable/apps && cp ./multimedia-volume-control.svg ./usr/share/icons/hicolor/scalable/apps

# MAKE APPIMAGE USING FUSE3 COMPATIBLE APPIMAGETOOL
cd .. && wget -q "$APPIMAGETOOL" -O ./appimagetool && chmod a+x ./appimagetool || exit 1
./appimagetool --appimage-extract-and-run deploy "$APPDIR"/usr/share/applications/*.desktop || exit 1
ARCH=x86_64 VERSION=$(echo "$REPO" | awk -F"_" '{print $(NF-1)}') ./appimagetool --appimage-extract-and-run -s ./"$APPDIR" || exit 1
[ -n "$APP" ] && mv ./*.AppImage .. && cd .. && rm -rf ./"$APP" || exit 1
echo "All done!"
```

You can run the appimage with the `--appimage-extract` flag to inspect inside of it and you will see that indeed several qt plugins were deployed but it still doesn't work.

What's worse is that with this appimage besides that icons are still broken, if you install qt5ct it no longer follows the system theme nor uses icons, it is permanently broken lol.

I need to report this at [go-appimage](https://github.com/probonopd/go-appimage)

**Comment by vinniec2** [comment] 2024-07-16 15:57
I wanted to try it but I can't find the ar archives decompressor !

**Comment by Samueru-sama** [comment] 2024-07-16 18:42
> I wanted to try it but I can't find the ar archives decompressor !

`sudo pacman -S binutils`

**Comment by vinniec2** [comment] 2024-07-16 21:42
Okay, your script worked, but you are right the icons are not showing.
I noticed that the three files I had mentioned to you though aren't in the same locations (the last one is also completely missing, even in a different version).
I now don't know if all systems expect those libraries in the same positions

**Comment by vinniec2** [comment] 2024-07-21 03:43
ok many thanks, I will try as soon as I understand how to compile the packages for android :D

**Comment by Samueru-sama** [comment] 2024-07-23 10:42
@vinniec2 Apparently I need to use linuxdeploy-qt (not to be confused with linuxdeploy + qt plugin) and use the `-extra-plugins` flag to add `iconengines,platformthemes/libqgtk3.so`

It would be something like this: 

```
#!/bin/sh

# TURNING THE NATIVE DEBIAN PACKAGE INTO AN APPIMAGE BECAUSE I CAN'T GET THIS TO COMPILE ON DEBIAN 20.04 KEK.
set -u
ARCH=x86_64
APP=pavucontrol-qt
APPDIR="$APP.AppDir"
REPO="http://ftp.us.debian.org/debian/pool/main/p/pavucontrol-qt/pavucontrol-qt_1.2.0-1_amd64.deb"
EXEC="$APP"
ICON="https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-icon-theme/master/Papirus/64x64/apps/yast-sound.svg"

LINUXDEPLOY="https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
APPIMAGETOOL=$(wget -q https://api.github.com/repos/probonopd/go-appimage/releases -O - | sed 's/[()",{} ]/\n/g' | grep -oi 'https.*continuous.*tool.*x86_64.*mage$' | head -1)

# CREATE DIRECTORIES
[ -n "$APP" ] && mkdir -p ./"$APP/$APPDIR"/tmp && cd ./"$APP/$APPDIR"/tmp || exit 1

# DOWNLOAD DEBIAN PACKAGE
CURRENTDIR="$(dirname "$(readlink -f "$0")")" # DO NOT MOVE THIS
wget $REPO && ar vx ./"$APP"* && tar fx ./data.tar* && mv ./usr .. && cd .. && rm -rf ./tmp || exit 1

# AppRun
cat >> ./AppRun << 'EOF'
#!/bin/sh
export LD_LIBRARY_PATH=/lib:/lib64:/lib/x86_64-linux-gnu:/usr/lib
CURRENTDIR="$(dirname "$(readlink -f "$0")")"
if [ -z "$QT_QPA_PLATFORMTHEME" ] && [ "$XDG_CURRENT_DESKTOP" != "KDE" ]; then # Not sure if this is the right way
	export QT_QPA_PLATFORMTHEME=gtk3
fi
"$CURRENTDIR/usr/bin/DUMMY" "$@"
EOF
sed -i "s|DUMMY|$EXEC|g" ./AppRun
chmod a+x ./AppRun
APPVERSION=$(./AppRun --version | awk 'FNR == 1 {print $2}')

# Desktop & Icon
cp ./usr/share/applications/*.desktop ./ && wget "$ICON" -O ./multimedia-volume-control.svg || exit 1
mkdir -p ./usr/share/icons/hicolor/scalable/apps && cp ./multimedia-volume-control.svg ./usr/share/icons/hicolor/scalable/apps

# MAKE APPIMAGE USING FUSE3 COMPATIBLE APPIMAGETOOL
export APPIMAGE_EXTRACT_AND_RUN=1
export ARCH=x86_64
cd .. && wget "$LINUXDEPLOY" -O linuxdeploy && wget -q "$APPIMAGETOOL" -O ./appimagetool
chmod a+x ./linuxdeploy ./appimagetool
VERSION=test ./linuxdeploy "$APPDIR"/usr/share/applications/*desktop -no-copy-copyright-files -extra-plugins=iconengines,platformthemes/libqgtk3.so || exit 1
VERSION=test ./appimagetool -s ./"$APPDIR" || exit 1
[ -n "$APP" ] && mv ./*.AppImage .. && cd .. && rm -rf ./"$APP" && echo "All Done!" || exit 1
```

The problem is that linuxdeploy-qt is hardcoded to work on `ubuntu-20.04` and some of the libraries that pavucontrol-qt needs are too old.

```
./pavucontrol-qt: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by ./pavucontrol-qt)
./pavucontrol-qt: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./pavucontrol-qt)
./pavucontrol-qt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./pavucontrol-qt)
```

So uh I don't know what do at this point, I think I will just add a warning on the AppRun that you need to have qt5ct installed on the system lol

**Comment by Samueru-sama** [comment] 2024-11-05 12:31
@vinniec2

Can you try the appimage now and let me know if you still have the issue?

**Comment by Samueru-sama** [comment] 2024-11-23 08:13
Well I will be closing this, if you still have the issue let me know.

**Closed by Samueru-sama** 2024-11-23 08:13 UTC
